# Generated by Django 4.0.3 on 2022-03-26 17:32

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComStCampProduced',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Name')),
                ('camp_comp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand Company Name')),
                ('camp_alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand Alias Name')),
                ('camp_logo', models.ImageField(blank=True, null=True, upload_to=product.models.brand_img_upload, verbose_name='Brand Photo')),
                ('camp_swift_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand Swift Code')),
                ('camp_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Brand Email')),
                ('camp_tel_one', models.CharField(blank=True, max_length=25, null=True, verbose_name='Brand Phone (1)')),
                ('camp_tel_two', models.CharField(blank=True, max_length=25, null=True, verbose_name='Brand Phone (2)')),
                ('camp_fax_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='Brand Fax')),
                ('camp_mob_one', models.CharField(blank=True, max_length=25, null=True, verbose_name='Brand Moblie (1)')),
                ('camp_mob_two', models.CharField(blank=True, max_length=25, null=True, verbose_name='Brand Moblie (2)')),
                ('camp_address_one', models.CharField(blank=True, max_length=300, null=True, verbose_name='Brand Address (1)')),
                ('camp_address_two', models.CharField(blank=True, max_length=300, null=True, verbose_name='Brand Address (2)')),
                ('camp_web', models.CharField(blank=True, max_length=200, null=True, verbose_name='Brand WebSite')),
                ('camp_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Contact')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'com_st_camp_produced',
                'ordering': ['camp_id'],
            },
        ),
        migrations.CreateModel(
            name='ComStClassDetails',
            fields=[
                ('class_d_no', models.AutoField(primary_key=True, serialize=False)),
                ('class_d_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Sub Name')),
                ('class_d_descraption', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Category Sub Descraption')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'com_st_class_details',
            },
        ),
        migrations.CreateModel(
            name='ComStClassMaster',
            fields=[
                ('class_m_no', models.AutoField(primary_key=True, serialize=False)),
                ('class_m_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Main Name')),
                ('class_m_descraption', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Category Descraption')),
                ('class_m_img', models.ImageField(blank=True, null=True, upload_to=product.models.category_img_upload, verbose_name='Category Photo')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'db_table': 'com_st_class_master',
                'ordering': ['class_m_no'],
            },
        ),
        migrations.CreateModel(
            name='ComStItemColors',
            fields=[
                ('item_c_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_c_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Name')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'com_st_item_colors',
            },
        ),
        migrations.CreateModel(
            name='ComStUnits',
            fields=[
                ('unit_no', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit Name')),
                ('unit_parameters', models.IntegerField(blank=True, null=True, verbose_name='Unit Parameter')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'com_st_units',
            },
        ),
        migrations.CreateModel(
            name='ComStProducts',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Product Name')),
                ('item_alias', models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Alias')),
                ('item_desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Product Descraption')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Code')),
                ('item_type_no', models.CharField(blank=True, choices=[('new', 'new'), ('used', 'used')], max_length=25, null=True, verbose_name='Product Type')),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Product Price')),
                ('have_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Serial')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('saling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Product Price Saling')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to=product.models.product_img_upload, verbose_name='Product Photo')),
                ('have_guarantee', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=100, null=True, verbose_name='Product Warranty')),
                ('guarantee_type', models.CharField(blank=True, choices=[('month', 'month'), ('year', 'year')], max_length=100, null=True, verbose_name='Product Warranty Date')),
                ('published_at_item', models.DateTimeField(auto_now=True)),
                ('item_comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Product Comment')),
                ('have_barcode', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=100, null=True, verbose_name='Product Barcode')),
                ('item_stok', models.IntegerField(blank=True, null=True, verbose_name='Product Stok')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('camp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.comstcampproduced', verbose_name='Brand Name')),
                ('class_d_no', models.ForeignKey(db_column='class_d_no', on_delete=django.db.models.deletion.CASCADE, to='product.comstclassdetails', verbose_name='Product Category Sub')),
                ('item_c_no', models.ForeignKey(blank=True, db_column='item_c_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.comstitemcolors', verbose_name='Product Color')),
                ('unit_no', models.ForeignKey(db_column='unit_no', on_delete=django.db.models.deletion.CASCADE, to='product.comstunits', verbose_name='Product Unit')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'com_st_products',
                'ordering': ['item_no'],
            },
        ),
        migrations.CreateModel(
            name='ComStItemImage',
            fields=[
                ('item_image_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_image_s', models.ImageField(blank=True, null=True, upload_to=product.models.product_img_upload, verbose_name='Product Photos')),
                ('item_no', models.ForeignKey(blank=True, db_column='item_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.comstproducts', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Photo',
                'verbose_name_plural': 'Product Photos',
                'db_table': 'com_st_item_image',
            },
        ),
        migrations.AddField(
            model_name='comstclassdetails',
            name='class_m_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.comstclassmaster', verbose_name='Category Main Name'),
        ),
        migrations.CreateModel(
            name='ComStAlternative_Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_alternative', models.ManyToManyField(related_name='item_alternative', to='product.comstproducts', verbose_name='Product Alternative')),
                ('item_no', models.ForeignKey(db_column='item_no', on_delete=django.db.models.deletion.CASCADE, related_name='item_alternative_no', to='product.comstproducts', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Product Alternatives',
                'db_table': 'com_st_alternative_pro',
            },
        ),
        migrations.CreateModel(
            name='ComStAccessories_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_alternative', models.ManyToManyField(related_name='item_accessories', to='product.comstproducts', verbose_name='Product Accessories')),
                ('item_no', models.ForeignKey(db_column='item_no', on_delete=django.db.models.deletion.CASCADE, related_name='item_accessories_no', to='product.comstproducts', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
                'db_table': 'com_st_accessories_pro',
            },
        ),
    ]
